workflows:
  android-debug:
    name: Android Debug APK

    environment:
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build Debug APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  android-release:
    name: Android Release AAB

    environment:
      android_signing:
        - sdtopup-release
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build Release AAB
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/bundle/release/*.aab